### ISSUE TITLE
ElasticSearch Sink - introduce configuration of the bulk feeder method.

### ISSUE THREAD

**Issue by ateska** [LibertyAces/BitSwanPump#112]
https://github.com/LibertyAces/BitSwanPump/blob/52c7c78582ba9dfa93c55285a8fb586980ea96d7/bspump/elasticsearch/connection.py#L119

Currently, there is a fixed & predefined approach to "create" or "index" action in the Bulk API.
I want to extend this mechanism to allow an user to configure what is his intention, which will specify what feeder method to use.

There are at least following candidates:

1. create
2. index
3. update
4. current [default]
5. delete
6. custom (callable provided)

**Comment by PremyslCerny** [comment]
https://github.com/LibertyAces/BitSwanPump/pull/115
