### ISSUE TITLE
Add an "ReducingSource"

### ISSUE THREAD

**Issue by ateska** [LibertyAces/BitSwanPump#13]
It is a special type of `InternalSource` but instead of Queue, there is an user-provided aggregation function.
It means that incoming events are aggregated by such a function (e.g. count, sum or moving average) and when the secondary pipeline (with `InternalSource`) is ready, it picks up that aggregation.

Possible scenario: the secondary pipeline is not saturated, so no aggregation is happening. Maybe some minimum number (of time and/or events) to be defined that enforces the aggregation if needed.

**Comment by margirova** [comment]
Can be extended to `MapReduceSource`, which allows to specify `map()` and `reduce()` functions or one of them can be `None`

**Comment by ateska** [comment]
Sure.
