### ISSUE TITLE
BSPUMP ElasticSearch Output Queue exceeds the output_queue_max_size if the pump is under pressure (the throttling fails)

### ISSUE THREAD

**Issue by PremyslCerny** [LibertyAces/BitSwanPump#189]
# Description

When running LogMan.io Depositor with 100k EPS, the Output Queue size in BSPUMP Elasticsearch Connection overflew the output_queue_max_size by approx. 6000, hence consuming the available memory.

The output_queue_max_size is set through ESConnection configuration: https://github.com/LibertyAces/BitSwanPump/blob/master/bspump/elasticsearch/connection.py#L258 

# Suspect: Throttling

The output queue limit should throttle the pipeline via the following scenario:

## 1. BSPUMP ElasticSearch Connection throttling

https://github.com/LibertyAces/BitSwanPump/blob/master/bspump/elasticsearch/connection.py

```
		# Signalize need for throttling
		if self._output_queue.qsize() == self._output_queue_max_size:
			self.PubSub.publish("ElasticSearchConnection.pause!", self)
```		

There may be a race condition with asynchronous _loader task:

https://github.com/LibertyAces/BitSwanPump/blob/master/bspump/elasticsearch/connection.py#L531

```
		if self._output_queue.qsize() == self._output_queue_max_size - 1:
			self.PubSub.publish("ElasticSearchConnection.unpause!", self)
```

## 2. Elasticsearch sink

https://github.com/LibertyAces/BitSwanPump/blob/master/bspump/elasticsearch/sink.py#L95

```
		app.PubSub.subscribe("ElasticSearchConnection.pause!", self._connection_throttle)
		app.PubSub.subscribe("ElasticSearchConnection.unpause!", self._connection_throttle)
```

## In LogMan.io Depositor

```
	def _connection_throttle(self, event_name, connection):
		if connection != self.Connection:
			return

		if event_name == "ElasticSearchConnection.pause!":
			self.Pipeline.throttle(self.PauseThrottler, True)
```

## First glance proposition

Replace

https://github.com/LibertyAces/BitSwanPump/blob/master/bspump/elasticsearch/connection.py

```
		# Signalize need for throttling
		if self._output_queue.qsize() == self._output_queue_max_size:
			self.PubSub.publish("ElasticSearchConnection.pause!", self)
```		

with:

```
		# Signalize need for throttling
		if self._output_queue.qsize() >= self._output_queue_max_size:
			self.PubSub.publish("ElasticSearchConnection.pause!", self)
```

To avoid race conditions.

**Comment by ateska** [comment]
1) 
> In LogMan.io Depositor

There should not be any extra code in the app to handle throttling.
`ElasticSearchConnection.pause!` & `ElasticSearchConnection.unpause!` are primarily used to be consumed by a Sink.
The sink then throttles the pipeline.

2) 
I agree that the condition check on `qsize()` is problematic.
