### ISSUE TITLE
Mysql lookup _count(self) is Broken

### ISSUE THREAD

**Issue by hrabalp** [LibertyAces/BitSwanPump#27]
following (valid) configuration breaks the lookup
`    ```
config = {
        'from': ' `DHCPSTATUS` JOIN RADIUS_USERDB_O2TV ON AP_SERVICEID = CETINSERVICEID JOIN RADIUSUSERS ON CASEID = TV ',
        'key': 'SUBNET',
        'statement': ' SUBNET, KRAJ, UNIX_TIMESTAMP() as lookup_fetch_time ',
    }
```
where `_count(self)` fetches mysql error ...
option to specify SQL template is questionable solution since we are uneable to modify arguments...

another point is what value this function actualy have since there are scenarios (like mine) where this function will say 250k ... but there is actualy only 10k uniqe key-value pairs ... since function is counting amount of rows but not uniqe rows so its questionable how reliable this is

**Comment by SukiCZ** [comment]
Is #20 related?

**Comment by hrabalp** [comment]
yes its related, but old code beforefixing issue 18 was not throwing mysql errors.

**Comment by ateska** [comment]
Closing as fixed.
