### ISSUE TITLE
Kafka Source default value for max_partition_fetch_bytes too high

### ISSUE THREAD

**Issue by hrabalp** [LibertyAces/BitSwanPump#30]
https://github.com/LibertyAces/BitSwanPump/blob/52ee17bd921d47bf97a509648906b5bc7efb33e4/bspump/kafka/source.py#L38

When there is more complex (slow ) processing in the pipeline it may timeout from kafka side and sourcre crashes (first commit gets error, retry fail as well)
Default value should be significantly more defensive (10% of current?)

User can allways incerease this value if he feels its required

**Comment by SukiCZ** [comment]
The value is the same as default in [aiokafka/consumer](https://github.com/aio-libs/aiokafka/blob/master/aiokafka/consumer/consumer.py#L224)
