### ISSUE TITLE
Add an option to specify input file charset encoding

### ISSUE THREAD

**Issue by ateska** [LibertyAces/BitSwanPump#6]
https://github.com/LibertyAces/BitSwanPump/blob/b683de32221431de8b5c2c52c491cde6e5843730/bspump/file/filecsvsource.py#L15

**Comment by ateska** [comment]
BitSwan internally works in UTF-8, if the CVS file is in other encoding, allow to specify that in a configuration.

**Comment by awichera** [comment]
I feel like I need for closer specification.

I am looking at FileABCSource from which FileCSVSource inherits, and it seems to implement config specified encoding for default source files.
```
f = open(locked_filename, self.mode, newline=self.newline,
						encoding=self.encoding if len(self.encoding) > 0 else None)
```

*I see two issues there*
1) There are special cases for `gzip`, `bz2` and `lzma` file formats, where encoding parametr is not passed.
```
if filename.endswith(".gz"):
	import gzip
	f = gzip.open(locked_filename, self.mode)
```

2) If user encoding is not provided in config, default python behaviour is invoked:
> if encoding is not specified the encoding used is platform dependent: locale.getpreferredencoding(False) is called to get the current locale encoding.
We might want to have `utf-8` as default instead.

- Do I read the situation well?
- Is one of these things the issue #6 or am I shooting off the target?
- If not should I fix them anyway?

**Comment by ateska** [comment]
1) "missing encoding for compressed formats" - please add them, then possible ... I remember that it was an issue with some, but `.gz` could be extended.
I guess, encoding conversion needs to happen in `FileABCSource`.

2) yes, if encoding is not provided, default python behavior is a correct way
I don't have too much details here - but the nature of the problem was, that people from our partner were not able to figure out, how to set an encoding for CVS file that was not in UTF-8. Maybe the answer is that they simply forget to look at `FileABCSource` options ... which seems to be logical, they are not expers.
Please extend compressed readers by encoding when available

**Comment by ateska** [comment]
@awichera - can this be closed?
